name: letsbeeclient
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.0
  font_awesome_flutter: ^8.11.0

  # Localization
  easy_localization: ^2.3.3
  
  # Badge
  badges: ^1.1.6

  # Loading animation
  loading_gifs: ^0.2.3

  # Dependency Injection
  get: ^3.26.0

  # Shared preference
  get_storage: ^1.4.0

  # Http request
  http: ^0.12.2

  # Svg 
  flutter_svg: ^0.19.1

  # Code Field
  code_field: ^1.22.0
  
  # Permission
  permission_handler: ^5.1.0+2

  # Keyboard visibility
  flutter_keyboard_visibility: ^4.0.6

  # Locations
  google_maps_flutter: ^1.2.0

  # geocoder: ^0.2.1
  geocoding: ^1.0.5
  location: ^3.2.4
  flutter_google_places: ^0.2.6

  # Slideable
  flutter_slidable: ^0.5.7

  # Notification builder
  flutter_local_notifications: ^4.0.1+1

  # Socket IO
  socket_io_client: ^0.9.12

  # Auto text resize
  auto_size_text: ^2.1.0

  # Webview
  webview_flutter: ^1.0.7

  # UUID
  uuid: ^2.2.2

  # Social logins
  kakao_flutter_sdk: ^0.5.4
  google_sign_in: ^4.5.9
  flutter_facebook_login: ^3.0.0
  sign_in_with_apple: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: false
  ios: true
  image_path_ios: "assets/ios/ic_launcher.png"
  image_path_android: "assets/android/ic_launcher.png"

flutter:

  uses-material-design: true

  assets:
    - assets/jsons/
    - assets/svg/
    - assets/png/
    - assets/gifs/
    - assets/translations/